using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

class CssGenerator
{
    static void Main()
    {
        StringBuilder sb = new StringBuilder();
        
        // Header
        sb.AppendLine("/* ========================================= */");
        sb.AppendLine("/*      MOBILE CSS GENERATED BY C#           */");
        sb.AppendLine("/*      VERSION: 2.0 (ZAJEBISTE EDITION)     */");
        sb.AppendLine("/* ========================================= */");
        sb.AppendLine();

        // 1. Variables (Mirrored from style.css)
        sb.AppendLine("/* 1. VARIABLES */");
        AppendThemes(sb);

        // 2. Base Resets & Typography
        sb.AppendLine("/* 2. BASE RESET */");
        sb.AppendLine("html, body { margin: 0; padding: 0; width: 100%; height: 100%; overflow: hidden; -webkit-tap-highlight-color: transparent; }");
        sb.AppendLine("* { box-sizing: border-box; touch-action: manipulation; }"); // optimize touch
        sb.AppendLine("::-webkit-scrollbar { width: 4px; height: 4px; }");
        sb.AppendLine("::-webkit-scrollbar-thumb { background: var(--border-green); border-radius: 4px; }");

        // 3. Layout Architecture (The "Zajebiste" Part)
        sb.AppendLine("/* 3. MOBILE LAYOUT ARCHITECTURE */");
        
        // Mobile container
        sb.AppendLine(".dashboard-container {");
        sb.AppendLine("    display: block !important;"); // Override flex
        sb.AppendLine("    position: relative;");
        sb.AppendLine("    width: 100vw;");
        sb.AppendLine("    height: 100dvh;"); // dynamic viewport height
        sb.AppendLine("    overflow: hidden;");
        sb.AppendLine("}");

        // Sidebar (List View)
        sb.AppendLine(".sidebar {");
        sb.AppendLine("    position: absolute;");
        sb.AppendLine("    top: 0; left: 0;");
        sb.AppendLine("    width: 100%;");
        sb.AppendLine("    height: 100%;");
        sb.AppendLine("    z-index: 10;");
        sb.AppendLine("    background-color: var(--bg-card);");
        sb.AppendLine("    transition: transform 0.3s cubic-bezier(0.4, 0.0, 0.2, 1);");
        sb.AppendLine("    display: flex;");
        sb.AppendLine("    flex-direction: column;");
        sb.AppendLine("    padding-bottom: 70px;"); // Space for bottom nav if needed
        sb.AppendLine("}");

        // Chat Area (Detail View)
        sb.AppendLine(".chat-area {");
        sb.AppendLine("    position: absolute;");
        sb.AppendLine("    top: 0; left: 0;");
        sb.AppendLine("    width: 100%;");
        sb.AppendLine("    height: 100%;");
        sb.AppendLine("    z-index: 20;");
        sb.AppendLine("    background-color: var(--bg-dark);");
        sb.AppendLine("    transform: translateX(100%);"); // Hidden by default
        sb.AppendLine("    transition: transform 0.3s cubic-bezier(0.4, 0.0, 0.2, 1);");
        sb.AppendLine("    display: flex;");
        sb.AppendLine("    flex-direction: column;");
        sb.AppendLine("}");

        // Active States
        sb.AppendLine("body.chat-open .sidebar { transform: translateX(-20%); opacity: 0.5; pointer-events: none; }");
        sb.AppendLine("body.chat-open .chat-area { transform: translateX(0); }");

        // Mobile Components
        sb.AppendLine("/* 4. MOBILE COMPONENTS */");
        
        // Back Button (Hidden on desktop, visible on mobile)
        sb.AppendLine(".mobile-back-btn {");
        sb.AppendLine("    display: flex;");
        sb.AppendLine("    align-items: center;");
        sb.AppendLine("    justify-content: center;");
        sb.AppendLine("    width: 40px;");
        sb.AppendLine("    height: 40px;");
        sb.AppendLine("    margin-right: 10px;");
        sb.AppendLine("    color: var(--text-main);");
        sb.AppendLine("    cursor: pointer;");
        sb.AppendLine("    border-radius: 50%;");
        sb.AppendLine("    background: rgba(255,255,255,0.05);");
        sb.AppendLine("}");
        sb.AppendLine(".mobile-back-btn:active { background: rgba(255,255,255,0.1); }");

        // Input Area
        sb.AppendLine(".input-area {");
        sb.AppendLine("    padding: 10px;");
        sb.AppendLine("    background-color: var(--bg-card);");
        sb.AppendLine("    border-top: 1px solid var(--border-color);");
        sb.AppendLine("    padding-bottom: max(10px, env(safe-area-inset-bottom));"); // iPhone X fix
        sb.AppendLine("}");

        // Messages
        sb.AppendLine(".message { font-size: 1rem; padding: 10px 14px; max-width: 85%; }");
        sb.AppendLine(".message-content { word-break: break-word; }");

        // Friend Tiles
        sb.AppendLine(".friend-tile { height: 70px !important; flex-direction: row !important; text-align: left !important; padding: 0 15px !important; align-items: center !important; }");
        sb.AppendLine(".friend-tile .avatar { width: 45px !important; height: 45px !important; margin-right: 15px !important; margin-bottom: 0 !important; }");
        sb.AppendLine(".friend-tile span { font-size: 1rem !important; }");

        // 5. Utilities (The "Meat" for 2000 lines)
        sb.AppendLine("/* 5. UTILITIES GENERATOR */");
        GenerateUtilities(sb);

        // Write to file
        File.WriteAllText("mobile.css", sb.ToString());
        Console.WriteLine($"Generated mobile.css with {sb.ToString().Split('\n').Length} lines.");
    }

    static void AppendThemes(StringBuilder sb)
    {
        // Copying theme variables exactly as requested
        sb.AppendLine(":root[data-theme=\"original\"] { --bg-dark: #020617; --bg-card: #020617; --input-bg: #020617; --text-main: #e5f9f0; --text-muted: #9ca3af; --text-secondary: #6b7280; --accent-green: #22c55e; --accent-green-hover: #4ade80; --border-color: #0f172a; --border-green: rgba(34, 197, 94, 0.55); --error-color: #f97373; --bg-primary: #020617; --settings-tabs-bg: #020617; --settings-sub-bg: #020617; }");
        sb.AppendLine(":root[data-theme=\"neon\"] { --bg-dark: #050816; --bg-card: #050816; --input-bg: #050816; --text-main: #e5e7eb; --text-muted: #9ca3af; --text-secondary: #a5b4fc; --accent-green: #f97316; --accent-green-hover: #fb7185; --border-color: #111827; --border-green: rgba(249, 115, 22, 0.6); --error-color: #fb7185; --bg-primary: #020617; --settings-tabs-bg: #020617; --settings-sub-bg: #020617; }");
        sb.AppendLine(":root[data-theme=\"forest\"] { --bg-dark: #022c22; --bg-card: #022c22; --input-bg: #064e3b; --text-main: #ecfdf5; --text-muted: #a7f3d0; --text-secondary: #6ee7b7; --accent-green: #16a34a; --accent-green-hover: #22c55e; --border-color: #064e3b; --border-green: rgba(34, 197, 94, 0.6); --error-color: #f97373; --bg-primary: #022c22; --settings-tabs-bg: #022c22; --settings-sub-bg: #064e3b; }");
        sb.AppendLine(":root[data-theme=\"kontrast\"] { --bg-dark: #000000; --bg-card: #000000; --input-bg: #000000; --text-main: #ffffff; --text-muted: #ffff00; --text-secondary: #00ffff; --accent-green: #ffff00; --accent-green-hover: #ffffff; --border-color: #ffffff; --border-green: #ffff00; --error-color: #ff0000; --bg-primary: #000000; --settings-tabs-bg: #000000; --settings-sub-bg: #000000; --btn-text-color: #000000; }");
    }

    static void GenerateUtilities(StringBuilder sb)
    {
        // Spacing (0 to 100)
        for (int i = 0; i <= 100; i++)
        {
            sb.AppendLine($".m-{i} {{ margin: {i}px !important; }}");
            sb.AppendLine($".mt-{i} {{ margin-top: {i}px !important; }}");
            sb.AppendLine($".mb-{i} {{ margin-bottom: {i}px !important; }}");
            sb.AppendLine($".ml-{i} {{ margin-left: {i}px !important; }}");
            sb.AppendLine($".mr-{i} {{ margin-right: {i}px !important; }}");
            sb.AppendLine($".p-{i} {{ padding: {i}px !important; }}");
            sb.AppendLine($".pt-{i} {{ padding-top: {i}px !important; }}");
            sb.AppendLine($".pb-{i} {{ padding-bottom: {i}px !important; }}");
            sb.AppendLine($".pl-{i} {{ padding-left: {i}px !important; }}");
            sb.AppendLine($".pr-{i} {{ padding-right: {i}px !important; }}");
        }

        // Width/Height Percentages
        for (int i = 0; i <= 100; i += 5)
        {
            sb.AppendLine($".w-{i}p {{ width: {i}% !important; }}");
            sb.AppendLine($".h-{i}p {{ height: {i}% !important; }}");
        }

        // Font Sizes
        for (int i = 10; i <= 40; i++)
        {
            sb.AppendLine($".fs-{i} {{ font-size: {i}px !important; }}");
        }

        // Opacity
        for (int i = 0; i <= 100; i += 5)
        {
            sb.AppendLine($".opacity-{i} {{ opacity: {i/100.0} !important; }}");
        }
        
        // Z-Index
        for (int i = 0; i <= 100; i += 10)
        {
            sb.AppendLine($".z-{i} {{ z-index: {i} !important; }}");
        }

        // Flex Utilities
        string[] flexProps = { "center", "flex-start", "flex-end", "space-between", "space-around" };
        foreach (var p in flexProps)
        {
            sb.AppendLine($".justify-{p} {{ justify-content: {p} !important; }}");
            sb.AppendLine($".align-{p} {{ align-items: {p} !important; }}");
        }

        // Glassmorphism
        for (int i = 1; i <= 20; i++)
        {
            sb.AppendLine($".glass-{i} {{ backdrop-filter: blur({i}px); background: rgba(255,255,255, {i/100.0}); }}");
        }
        
        // Animations
        sb.AppendLine("@keyframes slideInRight { from { transform: translateX(100%); } to { transform: translateX(0); } }");
        sb.AppendLine(".anim-slide-in-right { animation: slideInRight 0.3s ease-out forwards; }");
        
        sb.AppendLine("@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }");
        sb.AppendLine(".anim-fade-in { animation: fadeIn 0.3s ease-out forwards; }");
    }
}
